export const CLIENTES_INICIAIS = [
  { id: "anima", nome: "Ânima", contrato: null },
  { id: "cobranca-isaac", nome: "Cobrança- Isaac", contrato: null },
  { id: "cruzeiro-do-sul", nome: "Cruzeiro do Sul", contrato: null },
  { id: "educacional", nome: "Educacional", contrato: null },
  { id: "empresarial-cobranca", nome: "Empresarial - Cobrança", contrato: null },
  { id: "fiergs", nome: "FIERGS", contrato: "2026" },
  { id: "firjan", nome: "FIRJAN", contrato: "2026" },
  { id: "grupo-avenida", nome: "Grupo Avenida", contrato: null },
  { id: "receptivo", nome: "Receptivo", contrato: null },
  { id: "vero", nome: "Vero", contrato: null },
  { id: "yduqs", nome: "Yduqs", contrato: null },
];

export const OPERACOES_AVALIACAO_INICIAIS = CLIENTES_INICIAIS;

export const CAMPANHAS_INICIAIS = [
  "Ativo - Prospecção",
  "Ativo 20 a 44",
  "Ativo 45 a 75",
  "Ativo 76 a 120",
  "Campanha teste Raphael",
  "Canais Online (E-mail, Chat e WhatsApp)",
  "Chat",
  "E - Saúde Digital",
  "MONITORIAS IA",
  "Monitorias IA - Telefone Ativo",
  "Monitorias IA - Telefone Receptivo",
  "Odontologia e Massagem relaxante (Offline)",
  "Pré Churn - Telefone",
  "Telefone",
  "Telefone Ativo",
  "Telefone Receptivo",
  "Telefone ativo",
  "Teste receptivo",
  "Chat - Empresarial",
  "Telefone ativo Empresarial",
  "Isaac Ativo - Telefone",
  "Vero Churn",
  "Vero Churn - Telefone",
  "Vero Pré churn",
  "Vero2 - Bck",
  "teste 1 campanha",
];

export const AVALIADORES_INICIAIS = [
  "Gisele Oliveira",
  "Fábio Batista Oliveira",
  "Fernanda Alves",
  "Dayara Jovita",
  "Denise Esquivel",
  "Raphael Outstand",
  "Roberta Bruna Pereira Diniz",
];

export const AVALIADOS_INICIAIS = [
  "Camilly Vitoria Valerio da Silva",
  "Luana Santos de Oliveira",
  "Weslley da Silva Bessa",
  "Acassya Mota da Silva",
  "Adriana Monteiro Lima",
  "Ana Carolina Dutra Moraes",
  "Carlos Eduardo de Oliveira Nogueira",
  "Daniel Luiz Pina",
  "Felipe Silva Batista",
  "Gabriela Alves Machado",
  "Juliana Tavares",
  "Leonardo Nunes da Silva",
  "Marcia Lima Peixoto",
  "Mariana Nunes da Motta",
  "Renata Barros Ribeiro",
  "Thayana Brito Torres da Silva",
  "Valéria de Oliveira Alves",
];

export const CATEGORIAS_INICIAIS = ["Padrão", "Diagnóstico"];

export const DEPARTAMENTOS_INICIAIS = [
  "Administrador",
  "Gestor de Qualidade",
  "Coordenador",
  "Supervisor",
  "Monitor Sênior",
  "Monitor",
  "Monitor IA",
  "Analista de Qualidade",
  "Operador",
  "Auditor",
  "Visualizador",
];

export const MONITORES_IA_INICIAIS = [
  {
    id: "anima-ia",
    slug: "anima-ia",
    nome: "Ânima",
    cliente: "Ânima",
    campanhas: 1,
    campanhasNomes: "Telefone Ativo",
  },
  {
    id: "cobranca-isaac-ia",
    slug: "cobranca-isaac-ia",
    nome: "Cobrança- Isaac",
    cliente: "Cobrança- Isaac",
    campanhas: 1,
    campanhasNomes: "Isaac Ativo - Telefone",
  },
  {
    id: "cruzeiro-do-sul-ia",
    slug: "cruzeiro-do-sul-ia",
    nome: "Cruzeiro do Sul",
    cliente: "Cruzeiro do Sul",
    campanhas: 1,
    campanhasNomes: "Telefone Ativo",
  },
  {
    id: "educacional-ia",
    slug: "educacional-ia",
    nome: "Educacional",
    cliente: "Educacional",
    campanhas: 1,
    campanhasNomes: "Telefone Ativo",
  },
  {
    id: "empresarial-cobranca-ia",
    slug: "empresarial-cobranca-ia",
    nome: "Empresarial - Cobrança",
    cliente: "Empresarial - Cobrança",
    campanhas: 2,
    campanhasNomes: "Chat - Empresarial, Telefone ativo Empresarial",
  },
  {
    id: "fiergs-ia",
    slug: "fiergs-ia",
    nome: "FIERGS",
    cliente: "FIERGS",
    campanhas: 1,
    campanhasNomes: "Canais Online (E-mail, Chat e WhatsApp)",
  },
  {
    id: "firjan-ia",
    slug: "firjan-ia",
    nome: "FIRJAN",
    cliente: "FIRJAN",
    campanhas: 1,
    campanhasNomes: "Canais Online (E-mail, Chat e WhatsApp)",
  },
  {
    id: "grupo-avenida-ia",
    slug: "grupo-avenida-ia",
    nome: "Grupo Avenida",
    cliente: "Grupo Avenida",
    campanhas: 1,
    campanhasNomes: "Telefone Grupo Avenida",
  },
  {
    id: "receptivo-ia",
    slug: "receptivo-ia",
    nome: "Receptivo",
    cliente: "Receptivo",
    campanhas: 2,
    campanhasNomes: "Telefone Receptivo, Teste receptivo",
  },
  {
    id: "vero-ia",
    slug: "vero-ia",
    nome: "Vero",
    cliente: "Vero",
    campanhas: 4,
    campanhasNomes: "Vero Churn, Vero Churn - Telefone, Vero Pré churn, Vero2 - Bck",
  },
  {
    id: "yduqs-ia",
    slug: "yduqs-ia",
    nome: "Yduqs",
    cliente: "Yduqs",
    campanhas: 1,
    campanhasNomes: "Telefone Ativo",
  },
];
